[package]
name = "deno_graph"
version = "0.1.0"
edition = "2018"
description = "module graph analysis for deno"
authors = ["the Deno authors"]
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "deno_graph"

[dependencies]
anyhow = "1.0.42"
data-url = "0.1.0"
futures = "0.3.16"
js-sys = "0.3.51"
lazy_static = "1.4.0"
log = { version = "0.4.14", features = ["serde"] }
regex = "1.5.4"
ring = "0.16.20"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = { version = "1.0.66", features = ["preserve_order"] }
swc_common = "0.11.1"
swc_ecmascript = { version = "0.50.0", features = ["dep_graph", "parser"] }
url = { version = "2.2.2", features = ["serde"] }
wasm-bindgen = { version = "0.2.75", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.24"

[dev-dependencies]
tokio = { version = "1.9.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"
